name: lando-drupal-scaffold
config:
  framework: drupal8
  disableAutoComposerInstall: true
  site: scaffold
  id: 58ceb48b-e86e-4c4d-beac-a9a886371247

recipe: pantheon

services:
  node:
    type: node:6
    build:
      - "cd $LANDO_MOUNT && yarn"
  # @todo: need Blackfire.  See https://github.com/lando/lando/pull/634

tooling:
  yarn:
    service: node
  gulp:
    service: node
    cmd: node_modules/.bin/gulp
  phpunit:
    service: appserver
    cmd: cd $LANDO_MOUNT && vendor/bin/phpunit
  behat:
    service: appserver
    cmd: cd $LANDO_MOUNT && vendor/bin/behat
  # These are our "meta" level commands.
  build:
    service: node
    description: "Run all build steps"
    cmd: true
  lint:
    service: node
    description: "Run all linting steps"
    cmd: true
  test:
    service: node
    description: "Run all testing steps"
    cmd: true

events:
  post-build:
    - node: node_modules/.bin/gulp build
  post-lint:
    - node: node_modules/.bin/eslint .
    - appserver: cd $LANDO_MOUNT && composer validate
    - appserver: cd $LANDO_MOUNT && vendor/bin/phpcs
  post-test:
    - appserver: cd $LANDO_MOUNT && vendor/bin/behat
    - appserver: cd $LANDO_MOUNT && vendor/bin/phpunit
    # @todo: WDIO.
