language: php

services:
  - mysql

php:
  - 5.6
  - 7

cache:
  directories:
    - $HOME/.composer/cache

install:
  - nvm install
  - npm install
  - gulp install

script:
  - composer validate
  - gulp check
  - gulp build
  # Install site
  - cp ci/settings.travis.php web/sites/default/settings.local.php
  - vendor/bin/drush -r web/ si -y

