language: php

php:
  - 5.6
  - 7

cache:
  directories:
    - $HOME/.composer/cache

install:
  - nvm install
  - npm install
  - gulp install

script:
  - composer validate
  - gulp check
  - gulp build
