language: php

services:
  - mysql

php:
  - 5.6
  - 7

cache:
  directories:
    - $HOME/.composer/cache

install:
  - nvm install
  - npm install
  - gulp install
  - mysql -e "CREATE DATABASE drupal; CREATE USER 'drupal'@'localhost' IDENTIFIED BY 'drupal'; GRANT ALL ON drupal.* TO 'drupal'@'localhost'"


script:
  - composer validate
  - gulp check
  - gulp build
  - cp ci/settings.travis.php web/sites/default/settings.local.php && vendor/bin/drush -r web/ si -y --db-url=mysql://root@localhost/test

